#!/bin/bash

# check php port
if [ -z "$PHP_PORT" ]; then
	export PHP_PORT=9000
fi

# function to check php.ini config and bak
checkPhpIni() {
	if [[ $(cat ${DOCKER_ETC_DIR}/php${PHPV}/php.ini) =~ "^\s*$" ]]; then
		mv ${DOCKER_ETC_DIR}/php${PHPV}/php.ini.bak ${DOCKER_ETC_DIR}/php${PHPV}/php.ini
	else
		rm ${DOCKER_ETC_DIR}/php${PHPV}/php.ini.bak
	fi
}

# function to check fpm www pool and bak
checkPhpPool() {
	if [[ $(cat ${DOCKER_ETC_DIR}/php${PHPV}/php-fpm.d/www.conf) =~ "^\s*$" ]]; then
		mv ${DOCKER_ETC_DIR}/php${PHPV}/php-fpm.d/www.conf.bak ${DOCKER_ETC_DIR}/php${PHPV}/php-fpm.d/www.conf
	else
		rm ${DOCKER_ETC_DIR}/php${PHPV}/php-fpm.d/www.conf.bak
	fi
}

#
# set php variables
#
# PHP_MEMORY_LIMIT -> memory_limit
# PHP_ZLIB__OUTPUT_COMPRESSION -> zlib.output_compression
#
WWWVARS='[www]'
ENV_VARS=($(env))
for VAR in "${ENV_VARS[@]}"; do
	VAR_NAME=$(echo $VAR | cut -d'=' -f 1)
	VAR_VALUE=$(echo $VAR | cut -d'=' -f 2)
	if [[ $VAR_VALUE != "" ]]; then
		if [[ "$VAR_NAME" =~ "PHP_"* ]] && [[ "$VAR_NAME" != "PHP_PORT" ]]; then
			PHP_SETTING=$(echo $VAR_NAME | cut -d'_' -f 2-)
			PHP_SETTING=$(echo $PHP_SETTING | awk '{print tolower($0)}')
			PHP_SETTING=$(echo $PHP_SETTING | perl -pe "s/__/./")
			perl -p -i.bak -e "s/^$PHP_SETTING\s*=\s*.*/$PHP_SETTING = $(escape $VAR_VALUE)/gi" ${DOCKER_ETC_DIR}/php${PHPV}/php.ini
			checkPhpIni
		else
			WWWVARS="$WWWVARS"$'\n'"env[$VAR_NAME]=$VAR_VALUE"
		fi
	fi
done
echo "$WWWVARS" > ${DOCKER_ETC_DIR}/php${PHPV}/php-fpm.d/env.conf

# set php listen port
perl -p -i.bak -e "s/listen\s*=\s*(.+(:)?)?(.+)?/listen = $PHP_PORT/gi" ${DOCKER_ETC_DIR}/php${PHPV}/php-fpm.d/www.conf
checkPhpPool

# set timezone
perl -p -i.bak -e "s/;*date.timezone\s*=.*/date.timezone = $TIMEZONE/gi" ${DOCKER_ETC_DIR}/php${PHPV}/php.ini
checkPhpIni